Repository 7JEON8KI/frontend, pull requests merged in 2024-03, with the labels that each got.

#13 mypage (coupon, point) 퍼블리싱
  package-lock.json
  package.json
  src/components/mealkeat/mypage/Sidebar.tsx
  src/pages/mealkeat/mypage/PageMypage.style.ts
  src/pages/mealkeat/mypage/PageMypage.tsx
  src/pages/mealkeat/mypage/PageMypageCoupon.style.ts
  src/pages/mealkeat/mypage/PageMypageCoupon.tsx
  src/pages/mealkeat/mypage/PageMypagePoint.style.ts
  src/pages/mealkeat/mypage/PageMypagePoint.tsx
  src/routes/mealRoutes.tsx
Labels: ui/iux, 🍔 소민

#14 마이페이지(찜,리뷰,주문배송) 퍼블리싱 & api 연결
  src/apis/api.ts
  src/apis/likeApi.ts
  src/assets/images/icons/upload_icon.png
  src/components/mealkeat/mypage/Sidebar.tsx
  src/pages/mealkeat/mypage/ModalReview.tsx
  src/pages/mealkeat/mypage/PageMypage.tsx
  src/pages/mealkeat/mypage/PageMypageLike.style.ts
  src/pages/mealkeat/mypage/PageMypageLike.tsx
  src/pages/mealkeat/mypage/PageMypageOrder.tsx
  src/pages/mealkeat/mypage/PageMypageOrderDetail.tsx
  src/pages/mealkeat/mypage/PageMypageReview.tsx
Labels: feature, 🐥형준

#18 리액트 공통 모달 컨테이너 컴포넌트 --ISSUE-34
  .prettierrc
  package-lock.json
  package.json
  src/components/mealkeat/commons/ModalContainer.tsx
  src/components/mealkeat/commons/index.ts
  src/components/mealkeat/index.ts
  src/components/mealkeat/modal/CartModal.tsx
  src/components/mealkeat/modal/index.ts
  src/components/mealkeat/mypage/index.ts
  src/pages/mealkeat/product/PageDetail.tsx
Labels: feature, 🏋️‍♀️지윤

#19 찜 api 모두 연결 리뷰 페이지 분할
  src/apis/cartApi.ts
  src/apis/likeApi.ts
  src/components/mealkeat/commons/Header.tsx
  src/pages/mealkeat/mypage/MyReview.tsx
  src/pages/mealkeat/mypage/PageMypage.style.ts
  src/pages/mealkeat/mypage/PageMypageLike.tsx
  src/pages/mealkeat/mypage/PageMypageReview.tsx
  src/pages/mealkeat/mypage/Reviewable.tsx
Labels: feature, ui/iux, 🐥형준

#20 feat: 마이페이지 쿠폰 api 연결
  src/apis/MypageCouponApi.ts
  src/pages/mealkeat/mypage/PageMypageCoupon.style.ts
  src/pages/mealkeat/mypage/PageMypageCoupon.tsx
Labels: feature, 🍔 소민

#25 리뷰 api 연결
  src/apis/api.ts
  src/apis/orderHistoryApi.ts
  src/apis/reviewApi.ts
  src/pages/mealkeat/mypage/ModalReview.tsx
  src/pages/mealkeat/mypage/MyReview.tsx
  src/pages/mealkeat/mypage/PageMypageOrder.tsx
  src/pages/mealkeat/mypage/PageMypageOrderDetail.tsx
  src/pages/mealkeat/mypage/PageMypageReview.tsx
  src/pages/mealkeat/mypage/Reviewable.tsx
Labels: feature, 🐥형준

#26 밀킷 추천 페이지 api 연결 및 버그 수정
  src/apis/productApi.ts
  src/assets/images/ingredients/cheese.png
  src/assets/images/ingredients/chicken.png
  src/assets/images/ingredients/fish.png
  src/assets/images/ingredients/lamb.png
  src/assets/images/ingredients/meat.png
  src/assets/images/ingredients/milk.png
  src/assets/images/ingredients/mushroom.png
  src/assets/images/ingredients/namul.png
  src/assets/images/ingredients/noodle.png
  src/assets/images/ingredients/peach.png
  src/assets/images/ingredients/peanut.png
  src/assets/images/ingredients/seashell.png
  src/assets/images/ingredients/shrimp.png
  src/assets/images/ingredients/squid.png
  src/components/mealkeat/product/Product.tsx
  src/components/mealkeat/product/RecommendProduct.tsx
  src/constants/ingredientsConstants.ts
  src/models/mealkeat/ProductModels.ts
  src/pages/mealkeat/product/PageDetail.tsx
  src/pages/mealkeat/product/PageMealkeat.tsx
  src/pages/mealkeat/product/PageMealkeatResult.tsx
Labels: bug, feature, 🏋️‍♀️지윤

#27 feat: 리뷰 사진 업로드 및 삭제 구현
  package-lock.json
  src/apis/reviewApi.ts
  src/pages/mealkeat/mypage/ModalReview.tsx
Labels: feature, ui/iux, 🐥형준

#29 찜버튼 토글화
  src/components/mealkeat/product/Product.tsx
  src/pages/mealkeat/product/PageBest.tsx
  src/pages/mealkeat/product/PageDetail.tsx
  src/pages/mealkeat/product/PageList.tsx
  src/pages/mealkeat/product/PageSearchResult.tsx
  src/pages/mealkeat/product/PageTheme.tsx
  src/pages/mealkeat/product/PageWine.tsx
Labels: feature, 🐥형준

#32 상품 디테일 - 리뷰
  src/apis/reviewApi.ts
  src/pages/mealkeat/product/PageDetail.tsx
Labels: feature, ui/iux, 🐥형준

#33 상품 디테일 페이지 버그 및 기능 이슈 완료
  src/apis/api.ts
  src/apis/cartApi.ts
  src/apis/productApi.ts
  src/components/mealkeat/commons/Header.style.ts
  src/components/mealkeat/commons/Header.tsx
  src/components/mealkeat/commons/Image.tsx
  src/components/mealkeat/commons/Logo.tsx
  src/components/mealkeat/modal/CartModal.tsx
  src/components/mealkeat/product/Product.tsx
  src/components/mealkeat/product/RecommendProduct.tsx
  src/pages/mealkeat/cart/PageCart.tsx
  src/pages/mealkeat/commons/PageMain.style.ts
  src/pages/mealkeat/commons/PageMain.tsx
  src/pages/mealkeat/mypage/ModalReview.tsx
  src/pages/mealkeat/mypage/MyReview.tsx
  src/pages/mealkeat/mypage/PageMypageLike.style.ts
  src/pages/mealkeat/mypage/PageMypageLike.tsx
  src/pages/mealkeat/mypage/PageMypageOrder.tsx
  src/pages/mealkeat/mypage/PageMypageOrderDetail.tsx
  src/pages/mealkeat/mypage/Reviewable.tsx
  src/pages/mealkeat/payment/PagePayment.tsx
  src/pages/mealkeat/product/PageDetail.tsx
  src/pages/mealkeat/product/PageList.style.ts
  src/pages/mealkeat/product/PageMealkeat.tsx
  src/pages/mealkeat/product/PageMealkeatResult.tsx
  src/utils/formatCurrency.ts
Labels: bug, feature, 🏋️‍♀️지윤

#34 이미지 검색 조회 API 호출 후 성공 시 페이지 이동
  src/assets/images/sorry.png
  src/components/mealkeat/commons/Header.tsx
  src/components/mealkeat/commons/NoProduct.tsx
  src/components/mealkeat/commons/index.ts
  src/pages/mealkeat/mypage/ModalReview.tsx
  src/pages/mealkeat/product/PageMealkeatResult.tsx
  src/pages/mealkeat/product/PageSearchResult.tsx
  src/utils/scrollToTop.ts
Labels: feature, 🏋️‍♀️지윤

#38 결제 관련 기능 보완
  package-lock.json
  package.json
  src/apis/api.ts
  src/apis/couponApi.ts
  src/apis/paymentApi.ts
  src/models/mealkeat/CouponModels.ts
  src/pages/mealkeat/cart/PageCart.tsx
  src/pages/mealkeat/mypage/PageMypageCoupon.tsx
  src/pages/mealkeat/payment/PagePayment.style.ts
  src/pages/mealkeat/payment/PagePayment.tsx
  src/pages/mealkeat/payment/PagePaymentComplete.tsx
  src/pages/mealkeat/product/PageDetail.tsx
  src/utils/calculateDiscoundPrice.ts
  tsconfig.json
Labels: feature, 🏋️‍♀️지윤

#37 관리자 접근제어 및 상품 전시
  src/apis/boAdminApi.ts
  src/apis/boManagerApi.ts
  src/components/bo/commons/BoError.tsx
  src/components/bo/global/BestList.tsx
  src/pages/bo/admin/PageAdminMain.tsx
  src/routes/boRoutes.tsx
Labels: feature, 🐥형준

#40 feat: 회원가입
  package-lock.json
  package.json
  src/apis/memberApi.ts
  src/pages/mealkeat/oauth/PageSignup.tsx
Labels: feature, 🐥형준

#39 Top5 판매량 상품 및 대쉬보드
  src/apis/boManagerApi.ts
  src/components/bo/commons/BoManagerLayout.tsx
  src/components/bo/manager/RecentOrder.tsx
  src/components/bo/manager/TopProduct.tsx
  src/pages/bo/manager/PageManagerMain.tsx
Labels: help wanted, :+1: 은구

#41 Fix/css
  public/index.html
  src/components/mealkeat/commons/Header.style.ts
  src/components/mealkeat/commons/Layout.tsx
  src/components/mealkeat/mypage/Sidebar.style.ts
  src/components/mealkeat/product/Product.style.ts
  src/components/mealkeat/product/Product.tsx
  src/components/mealkeat/product/ProductSidebar.tsx
  src/components/mealkeat/product/index.ts
  src/pages/mealkeat/cart/PageCart.tsx
  src/pages/mealkeat/mypage/ModalReview.tsx
  src/pages/mealkeat/mypage/MyReview.tsx
  src/pages/mealkeat/mypage/PageMypage.style.ts
  src/pages/mealkeat/mypage/PageMypageLike.style.ts
  src/pages/mealkeat/mypage/PageMypageLike.tsx
  src/pages/mealkeat/mypage/PageMypageOrder.tsx
  src/pages/mealkeat/mypage/PageMypageReview.tsx
  src/pages/mealkeat/payment/PagePayment.tsx
  src/pages/mealkeat/product/PageBest.tsx
  src/pages/mealkeat/product/PageDetail.tsx
  src/pages/mealkeat/product/PageList.style.ts
  src/pages/mealkeat/product/PageList.tsx
  src/pages/mealkeat/product/PageSearchResult.tsx
  src/pages/mealkeat/product/PageTheme.tsx
  src/pages/mealkeat/product/PageWine.tsx
Labels: 🏋️‍♀️지윤, ui/iux

#43 리덕스 사용해서 전역처리
  package.json
  src/App.tsx
  src/apis/api.ts
  src/components/mealkeat/commons/Header.tsx
  src/components/mealkeat/mypage/Sidebar.style.ts
  src/components/mealkeat/product/Product.tsx
  src/components/mealkeat/product/ProductSidebar.tsx
  src/components/mealkeat/product/RecommendProduct.tsx
  src/feature/cartSlice.ts
  src/feature/loginSlice.ts
  src/feature/recentProductSlice.ts
  src/hooks.ts
  src/pages/mealkeat/cart/PageCart.tsx
  src/pages/mealkeat/mypage/MyReview.tsx
  src/pages/mealkeat/mypage/PageMypageCoupon.style.ts
  src/pages/mealkeat/mypage/PageMypageCoupon.tsx
  src/pages/mealkeat/mypage/PageMypageLike.tsx
  src/pages/mealkeat/oauth/KakaoCallback.tsx
  src/pages/mealkeat/product/PageDetail.tsx
  src/store.ts
Labels: feature, 🏋️‍♀️지윤

#42 화면 레이아웃 수정
  src/apis/excelApi.ts
  src/components/bo/commons/BoEventAdd.tsx
  src/components/bo/commons/BoManagerModal.tsx
  src/components/bo/commons/BoProductModal.tsx
  src/components/bo/global/BestList.tsx
  src/components/bo/graph/SearchChart.tsx
  src/components/bo/manager/BoOrderModal.tsx
  src/components/bo/manager/BoOrderTable.tsx
  src/pages/bo/admin/PageAdminMain.tsx
  src/pages/bo/manager/PageManagerMain.tsx
  src/pages/bo/manager/PageManagerOrder.tsx
Labels: ui/iux, :+1: 은구

#44 테마별 css 수정 및 전성분 표시
  src/apis/productApi.ts
  src/components/mealkeat/product/Product.style.ts
  src/components/mealkeat/product/Product.tsx
  src/constants/productConstants.ts
  src/pages/mealkeat/commons/PageMain.tsx
  src/pages/mealkeat/product/PageDetail.tsx
  src/pages/mealkeat/product/PageList.style.ts
  src/pages/mealkeat/product/PageTheme.tsx
  src/styles/theme.ts
Labels: 🏋️‍♀️지윤, ui/iux

#45 어드민 페이지 대쉬보드 수정
  package-lock.json
  src/components/bo/graph/SearchChart.tsx
  src/components/bo/manager/ProductForm.tsx
  src/pages/bo/admin/PageAdminMain.tsx
Labels: ui/iux

#49 사이드바 색상, 로고 색상 변경
  src/assets/images/logo_white.png
  src/components/bo/commons/BoLayout.tsx
  src/components/bo/commons/BoManagerLayout.tsx
  src/components/bo/commons/BoManagerNav.tsx
  src/components/bo/commons/BoNav.tsx
  src/components/bo/global/BestList.tsx
  src/components/bo/global/BoIcon.tsx
  src/components/bo/graph/SearchChart.tsx
  src/components/bo/manager/ProductForm.tsx
  src/components/bo/manager/TopProduct.tsx
  src/pages/bo/admin/PageAdminMain.tsx
  src/pages/bo/manager/PageManagerMain.tsx
  src/pages/bo/manager/PageManagerOrder.tsx
  src/pages/bo/manager/PageManagerProduct.tsx
  src/pages/bo/manager/PageManagerProductInsert.tsx
Labels: ui/iux

#50 모달 깜빡임 수정
  src/pages/mealkeat/commons/PageMain.tsx
Labels: bug, 🏋️‍♀️지윤

#51 이벤트 관리 레이아웃 변경
  src/components/bo/commons/BoEventAdd.tsx
  src/components/bo/commons/BoNav.tsx
  src/pages/bo/admin/PageAdminEvent.tsx
  src/pages/bo/admin/PageAdminManager.tsx
Labels: ui/iux, :+1: 은구

#52 폼 레이아웃 수정
  src/components/bo/manager/ProductForm.tsx
  src/pages/bo/manager/PageManagerProductInsert.tsx
Labels: ui/iux, :+1: 은구
