Repository 7JEON8KI/frontend, pull requests merged in 2024-02, with the labels that each got.

#1 Feat: 환경설정 및 메인 화면 UI
  .eslintrc.json
  .gitignore
  .prettierrc
  .vscode/settings.json
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.test.tsx
  src/App.tsx
  src/assets/images/icons/Cart.png
  src/assets/images/icons/Heart.png
  src/assets/images/icons/Menu.png
  src/assets/images/icons/Search.png
  src/assets/images/icons/User.png
  src/assets/images/logo.png
  src/components/commons/Footer.tsx
  src/components/commons/Logo.tsx
  src/components/commons/TopNav.tsx
  src/index.css
  src/index.tsx
  src/logo.svg
  src/pages/PageMain.tsx
  src/pages/index.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/routes/mealRoutes.tsx
  src/setupTests.ts
  src/styles/GlobalStyle.ts
  src/styles/theme.ts
  tailwind.config.js
  tsconfig.json
Labels: 🏋️‍♀️지윤, ui/iux

#2 메인 페이지 슬라이더 퍼블 작업
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  src/assets/images/logo.png
  src/components/commons/Footer.tsx
  src/components/commons/Header.tsx
  src/components/commons/Layout.tsx
  src/components/commons/Logo.tsx
  src/components/commons/TopNav.tsx
  src/index.tsx
  src/pages/PageMain.tsx
  src/styles/GlobalStyle.ts
  src/styles/components/commons/Footer.style.ts
  src/styles/components/commons/Header.style.ts
  src/styles/components/commons/Layout.style.ts
  src/styles/components/commons/Logo.style.ts
  src/styles/pages/PageMain.style.ts
  src/styles/theme.ts
Labels: 🏋️‍♀️지윤, ui/iux

#3 Feat/publishing issue 47
  .eslintrc.json
  package-lock.json
  package.json
  public/logo192.png
  src/App.tsx
  src/assets/images/kakao_login_large_wide.png
  src/components/bo/index.ts
  src/components/mealkeat/commons/Footer.style.ts
  src/components/mealkeat/commons/Footer.tsx
  src/components/mealkeat/commons/Header.style.ts
  src/components/mealkeat/commons/Header.tsx
  src/components/mealkeat/commons/Layout.style.ts
  src/components/mealkeat/commons/Layout.tsx
  src/components/mealkeat/commons/Logo.style.ts
  src/components/mealkeat/commons/Logo.tsx
  src/components/mealkeat/commons/index.ts
  src/components/mealkeat/index.ts
  src/components/mealkeat/product/Product.tsx
  src/components/mealkeat/product/index.ts
  src/pages/bo/index.ts
  src/pages/index.tsx
  src/pages/mealkeat/commons/PageMain.style.ts
  src/pages/mealkeat/commons/PageMain.tsx
  src/pages/mealkeat/commons/index.ts
  src/pages/mealkeat/index.ts
  src/pages/mealkeat/mypage/PageMypage.tsx
  src/pages/mealkeat/mypage/index.ts
  src/pages/mealkeat/oauth/PageFail.tsx
  src/pages/mealkeat/oauth/PageLogin.tsx
  src/pages/mealkeat/oauth/PageSignup.tsx
  src/pages/mealkeat/oauth/index.ts
  src/pages/mealkeat/product/PageDetail.tsx
  src/pages/mealkeat/product/PageList.tsx
  src/pages/mealkeat/product/index.ts
  src/routes/boRoutes.tsx
  src/routes/mealRoutes.tsx
  src/styles/GlobalStyle.ts
  tsconfig.json
  webpack.config.cjs
Labels: 🏋️‍♀️지윤, ui/iux

#4 의존성 문제 해결
  package-lock.json
  package.json
Labels: 🏋️‍♀️지윤

#5 로그인 백엔드 통신
  src/pages/mealkeat/commons/PageMain.tsx
  src/pages/mealkeat/oauth/KakaoCallback.tsx
  src/pages/mealkeat/oauth/PageLogin.tsx
  src/routes/mealRoutes.tsx
  webpack.config.cjs
Labels: feature, 🐥형준

#6 상품 조회페이지 퍼블리싱
  src/assets/images/icons/except.png
  src/assets/images/icons/except_click.png
  src/components/mealkeat/product/Product.style.ts
  src/components/mealkeat/product/Product.tsx
  src/pages/mealkeat/commons/PageMain.style.ts
  src/pages/mealkeat/commons/PageMain.tsx
  src/pages/mealkeat/product/PageList.tsx
Labels: 🏋️‍♀️지윤, ui/iux

#7 도커 관련 파일 생성 및 dependency 버전 체크
  .dockerignore
  .gitignore
  Dockerfile
  nginx.conf
  package-lock.json
  package.json
Labels: feature, 🐥형준

#9 장바구니, 결제 퍼블리싱
  src/components/mealkeat/commons/Footer.style.ts
  src/components/mealkeat/commons/LoadingSpinner.style.ts
  src/components/mealkeat/commons/LoadingSpinner.tsx
  src/constants/productConstants.ts
  src/pages/mealkeat/cart/PageCart.tsx
  src/pages/mealkeat/commons/PageMain.style.ts
  src/pages/mealkeat/commons/PageMain.tsx
  src/pages/mealkeat/oauth/KakaoCallback.tsx
  src/pages/mealkeat/payment/PagePayment.tsx
  src/pages/mealkeat/payment/PagePaymentComplete.tsx
  src/pages/mealkeat/product/PageBest.tsx
  src/pages/mealkeat/product/PageList.style.ts
  src/styles/GlobalStyle.ts
  src/styles/theme.ts
  src/utils/formatCurrency.ts
Labels: 🏋️‍♀️지윤, ui/iux

#10 feat: 로그인 확인
  src/pages/mealkeat/oauth/KakaoCallback.tsx
Labels: feature, 🐥형준

#11 디테일 페이지 퍼블리싱
  public/index.html
  src/components/mealkeat/commons/Footer.style.ts
  src/components/mealkeat/commons/Header.style.ts
  src/components/mealkeat/commons/Header.tsx
  src/components/mealkeat/product/Product.style.ts
  src/components/mealkeat/product/Product.tsx
  src/pages/mealkeat/commons/PageMain.tsx
  src/pages/mealkeat/product/PageDetail.tsx
  src/styles/GlobalStyle.ts
  src/styles/theme.ts
Labels: 🏋️‍♀️지윤, ui/iux
